# Site settings
title: You can code better than this...
email: alex@riot-gear.net
description: > # this means to ignore newlines until "baseurl:"
  Another site by another software engineer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.riot-gear.net" # the base hostname & protocol for your site
twitter_username: alexdugger
github_username:  dugger

# Build settings
markdown: kramdown
